version: "3"
services:
  files-reader-back:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/backend
    container_name: files-reader-back
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev